export const APP_TOAST = 'APP_TOAST';

// 主题
export const TOPICS_LOAD_REQUEST = 'TOPICS_LOAD_REQUEST';
export const TOPICS_LOAD_FAILURE = 'TOPICS_LOAD_FAILURE';
export const TOPICS_LOAD_SUCCESS = 'TOPICS_LOAD_SUCCESS';
export const TOPIC_LOAD_REQUEST = 'TOPIC_LOAD_REQUEST';
export const TOPIC_LOAD_FAILURE = 'TOPIC_LOAD_FAILURE';
export const TOPIC_LOAD_SUCCESS = 'TOPIC_LOAD_SUCCESS';
export const TOPIC_COLLECT_REQUEST = 'TOPIC_COLLECT_REQUEST';
export const TOPIC_COLLECT_FAILURE = 'TOPIC_COLLECT_FAILURE';
export const TOPIC_COLLECT_SUCCESS = 'TOPIC_COLLECT_SUCCESS';
export const REPLY_LIKE_REQUEST = 'REPLY_LIKE_REQUEST';
export const REPLY_LIKE_FAILURE = 'REPLY_LIKE_FAILURE';
export const REPLY_LIKE_SUCCESS = 'REPLY_LIKE_SUCCESS';

// 消息
export const MESSAGE_LOAD_REQUEST = 'MESSAGE_LOAD_REQUEST';
export const MESSAGE_LOAD_FAILURE = 'MESSAGE_LOAD_FAILURE';
export const MESSAGE_LOAD_SUCCESS = 'MESSAGE_LOAD_SUCCESS';
export const MESSAGE_MARK_READ = 'MESSAGE_MARK_READ';

// 用户
export const USER_LOAD_REQUEST = 'USER_LOAD_REQUEST';
export const USER_LOAD_FAILURE = 'USER_LOAD_FAILURE';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USRE_LOGOUT = 'USRE_LOGOUT';
