'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var APP_TOAST = exports.APP_TOAST = 'APP_TOAST';

// 主题
var TOPICS_LOAD_REQUEST = exports.TOPICS_LOAD_REQUEST = 'TOPICS_LOAD_REQUEST';
var TOPICS_LOAD_FAILURE = exports.TOPICS_LOAD_FAILURE = 'TOPICS_LOAD_FAILURE';
var TOPICS_LOAD_SUCCESS = exports.TOPICS_LOAD_SUCCESS = 'TOPICS_LOAD_SUCCESS';
var TOPIC_LOAD_REQUEST = exports.TOPIC_LOAD_REQUEST = 'TOPIC_LOAD_REQUEST';
var TOPIC_LOAD_FAILURE = exports.TOPIC_LOAD_FAILURE = 'TOPIC_LOAD_FAILURE';
var TOPIC_LOAD_SUCCESS = exports.TOPIC_LOAD_SUCCESS = 'TOPIC_LOAD_SUCCESS';
var TOPIC_COLLECT_REQUEST = exports.TOPIC_COLLECT_REQUEST = 'TOPIC_COLLECT_REQUEST';
var TOPIC_COLLECT_FAILURE = exports.TOPIC_COLLECT_FAILURE = 'TOPIC_COLLECT_FAILURE';
var TOPIC_COLLECT_SUCCESS = exports.TOPIC_COLLECT_SUCCESS = 'TOPIC_COLLECT_SUCCESS';
var REPLY_LIKE_REQUEST = exports.REPLY_LIKE_REQUEST = 'REPLY_LIKE_REQUEST';
var REPLY_LIKE_FAILURE = exports.REPLY_LIKE_FAILURE = 'REPLY_LIKE_FAILURE';
var REPLY_LIKE_SUCCESS = exports.REPLY_LIKE_SUCCESS = 'REPLY_LIKE_SUCCESS';

// 消息
var MESSAGE_LOAD_REQUEST = exports.MESSAGE_LOAD_REQUEST = 'MESSAGE_LOAD_REQUEST';
var MESSAGE_LOAD_FAILURE = exports.MESSAGE_LOAD_FAILURE = 'MESSAGE_LOAD_FAILURE';
var MESSAGE_LOAD_SUCCESS = exports.MESSAGE_LOAD_SUCCESS = 'MESSAGE_LOAD_SUCCESS';
var MESSAGE_MARK_READ = exports.MESSAGE_MARK_READ = 'MESSAGE_MARK_READ';

// 用户
var USER_LOAD_REQUEST = exports.USER_LOAD_REQUEST = 'USER_LOAD_REQUEST';
var USER_LOAD_FAILURE = exports.USER_LOAD_FAILURE = 'USER_LOAD_FAILURE';
var USER_LOAD_SUCCESS = exports.USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
var USER_LOGIN_REQUEST = exports.USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
var USER_LOGIN_FAILURE = exports.USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
var USER_LOGIN_SUCCESS = exports.USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
var USRE_LOGOUT = exports.USRE_LOGOUT = 'USRE_LOGOUT';